# Generated by Django 5.2.4 on 2025-07-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalreport',
            name='report_image',
            field=models.ImageField(blank=True, null=True, upload_to='global_reports_image/'),
        ),
    ]
