# Generated by Django 5.2.4 on 2025-09-27 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lose_history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='losecategory',
            name='description',
        ),
    ]
