# Generated by Django 5.2.4 on 2025-08-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('staff', 'Staff'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
