# Generated by Django 5.2.4 on 2025-08-17 05:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_is_active_user_is_admin_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='count',
            field=models.IntegerField(default=0, help_text='Number of OTPs sent'),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='validated',
            field=models.BooleanField(default=False, help_text='If true, that means the user has validated OTP correctly.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Phone number must be 10 digits only.')]),
        ),
    ]
