# Generated by Django 5.2.4 on 2025-08-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_phone_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='business_type',
            field=models.CharField(choices=[('POULTRY', 'Poultry'), ('GROCERY', 'Grocery')], default='POULTRY', help_text='Select either Poultry or Grocery', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='count',
            field=models.IntegerField(default=0, help_text='Number of otp sent'),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='validated',
            field=models.BooleanField(default=False, help_text='If it is true, that means user has validated otp correctly in second API'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('staff', 'Staff'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
