# Generated by Django 5.2.4 on 2025-08-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('staff', 'Staff'), ('admin', 'Admin'), ('custom_admin', 'Custom_admin')], default='user', max_length=20),
        ),
    ]
