# Generated by Django 5.2.4 on 2025-08-11 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transactionitem_base_price_at_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='pieces_count',
            field=models.IntegerField(blank=True, help_text='Number of pieces for hen stock tracking', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
