# Generated by Django 5.2.4 on 2025-08-12 04:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transactionitem_pieces_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='pieces_count',
            field=models.IntegerField(blank=True, help_text='Number of pieces for stock tracking', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
