# Generated by Django 5.2.4 on 2025-08-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_transactionitem_pieces_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionitem',
            name='weight_kg',
        ),
    ]
