# Generated by Django 5.2.4 on 2025-07-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalnotes',
            name='note_type',
            field=models.CharField(choices=[('admin_to_owner', 'Admin To Owner'), ('owner_to_admin', 'Owner To Admin'), ('owner_to_employee', 'Owner To Employee'), ('employee_to_owner', 'Employee To Owner'), ('own_to_own', 'Own To Own')], max_length=50),
        ),
    ]
