# Generated by Django 5.2.4 on 2025-07-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_notes', '0002_alter_personalnotes_note_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalnotes',
            name='note_type',
        ),
        migrations.RemoveField(
            model_name='personalnotes',
            name='recipient_id',
        ),
        migrations.RemoveField(
            model_name='personalnotes',
            name='sender_id',
        ),
        migrations.AddField(
            model_name='personalnotes',
            name='note_title',
            field=models.CharField(default=555, max_length=150),
            preserve_default=False,
        ),
    ]
