# Generated by Django 5.2.4 on 2025-07-23 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_notes', '0004_personalnotes_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalnotes',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Personal Notes'},
        ),
    ]
