# Generated by Django 5.2.4 on 2025-07-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='discount_value',
            field=models.IntegerField(help_text='Discount value, percentage or fixed amount'),
        ),
    ]
