# Generated by Django 5.2.4 on 2025-07-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0002_customersubscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplans',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
