# Generated by Django 5.2.4 on 2025-07-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0003_subscriptionplans_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubscriptions',
            name='subscription_mode',
            field=models.CharField(choices=[('trial', 'Trial'), ('regular', 'Regular'), ('loan', 'Loan'), ('free', 'Free')], default='regular', max_length=10),
        ),
    ]
