# Generated by Django 5.2.4 on 2025-07-23 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0004_customersubscriptions_subscription_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customersubscriptions',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Customer Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplans',
            options={'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.AlterUniqueTogether(
            name='customersubscriptions',
            unique_together={('user_id', 'plan_id', 'start_date')},
        ),
        migrations.AlterField(
            model_name='customersubscriptions',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.CreateModel(
            name='SubscriptionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10)),
                ('payment_method', models.CharField(choices=[('bank', 'Bank'), ('agent', 'Agent')], max_length=10)),
                ('subscription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription_plans.customersubscriptions')),
            ],
            options={
                'verbose_name_plural': 'Subscription Orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.RemoveField(
            model_name='customersubscriptions',
            name='payment_method',
        ),
    ]
