# Generated by Django 5.2.4 on 2025-07-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0005_alter_customersubscriptions_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionorder',
            name='refrerence_number',
            field=models.CharField(default=55, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
