# Generated by Django 5.2.4 on 2025-07-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0006_subscriptionorder_refrerence_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersubscriptions',
            old_name='amount',
            new_name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='subscriptionorder',
            name='refrerence_number',
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='reference_number',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
