# Generated by Django 5.2.4 on 2025-07-24 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0008_remove_subscriptionorder_subscription_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionorder',
            name='subscription_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subscription_plans.subscriptionplans'),
            preserve_default=False,
        ),
    ]
