# Generated by Django 5.2.4 on 2025-08-11 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='pieces_count',
            field=models.IntegerField(default=0, help_text='Number of pieces for hen stock tracking', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
