# Generated by Django 5.2.4 on 2025-08-12 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_add_pieces_count_to_shopproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='pieces_count',
            field=models.IntegerField(default=0, help_text='Number of pieces for stock tracking', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
